services:
  db:
    image: postgres:16-alpine
    container_name: barbearia-db
    environment:
      - POSTGRES_USER: admin
      - POSTGRES_PASSWORD: password
      - POSTGRES_DB: barbearia
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  cache:
    image: redis:7-alpine
    container_name: barbearia-cache
    ports:
      - "6379:6379"

volumes:
  pgdata:
